# Generated by Django 2.2.5 on 2022-01-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_pw', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=10)),
            ],
        ),
    ]
