# Generated by Django 2.2.5 on 2022-01-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=700)),
                ('img', models.CharField(blank=True, max_length=700, null=True)),
                ('user_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'diary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=500)),
                ('professor_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lecture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=800)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=150)),
                ('job_fields', models.CharField(max_length=200)),
                ('required_career', models.CharField(max_length=200)),
                ('required_education', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=50)),
                ('work_place', models.CharField(max_length=200)),
                ('deadlines', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'recruit',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
