# Generated by Django 2.2.5 on 2022-01-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_auto_20220124_1246'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
