# Generated by Django 2.2.5 on 2022-01-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0003_auto_20220124_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': False, 'ordering': ['-date']},
        ),
    ]
